# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'schicht_storyboard' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for schicht_storyboard
  pod 'Alamofire', '~> 4.7'
  pod 'ViewPager-Swift'
  pod 'FSCalendar'

  target 'schicht_storyboardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'schicht_storyboardUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
