# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'schichtln' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for schichtln

 pod 'Alamofire', '~> 4.7'
 pod 'ViewPager-Swift'

  target 'schichtlnTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'schichtlnUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
